version: '3'

services:
   web:
    build:
      context: .   #build from current directory
      dockerfile: dockerfile.node
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development 
   mongo:
    build:
     context: .
     dockerfile: dockerfile.mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword